version: 2
tools:
  vim-vint:
    lint-command: 'vint --color'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %m'

  markdown-markdownlint:
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'
      - '%f:%l%c %m'
      - '%f: %l: %m'
