nnoremap   <buffer><silent>   <M-7>    :FloatermNew<CR>
tnoremap   <buffer><silent>   <M-7>    <C-\><C-n>:FloatermNew<CR>
nnoremap   <buffer><silent>   <M-p>    :FloatermPrev<CR>
tnoremap   <buffer><silent>   <M-p>    <C-\><C-n>:FloatermPrev<CR>
nnoremap   <buffer><silent>   <M-n>    :FloatermNext<CR>
tnoremap   <buffer><silent>   <M-n>    <C-\><C-n>:FloatermNext<CR>
nnoremap   <buffer><silent>   <M-t>   :FloatermToggle<CR>
tnoremap   <buffer><silent>   <M-t>   <C-\><C-n>:FloatermToggle<CR>
nnoremap   <buffer><silent>   <Esc>   :FloatermToggle<CR>
nnoremap   <buffer><silent>   q   :FloatermKill<CR>
tnoremap   <buffer><silent>   <Esc>   <C-\><C-n><CR>
tnoremap   <buffer><silent>   <M-q>   <C-\><C-n>:FloatermKill<CR>
